name: Build and Release Github Actions Image

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-runner:
    runs-on: RISCV64
    env:
      VERSION: 2.331.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Ubuntu latest Docker Image
        run: |

          echo "Building Docker image with Ubuntu LTS"
          podman build \
            -f Dockerfile.ubuntu \
            -t github-actions-riscv:ubuntu-${VERSION} \
            .
        
      - name: Push Ubuntu latest Docker Image
        run: |
          
          # Tag ubuntu image
          podman tag localhost/github-actions-riscv:ubuntu-${VERSION} docker.io/${{ secrets.DOCKERHUB_USERNAME }}/github-actions-riscv:ubuntu-${VERSION}
          podman tag localhost/github-actions-riscv:ubuntu-${VERSION} docker.io/${{ secrets.DOCKERHUB_USERNAME }}/github-actions-riscv:latest

          # Login to Docker Hub
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | podman login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

          # Push all tags
          podman push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/github-actions-riscv:ubuntu-${VERSION}
          podman push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/github-actions-riscv:latest
      - name: Build Debian Trixie Docker Image
        run: |

          echo "Building Docker image with Debian Trixie"
          podman build \
            -f Dockerfile.debian \
            -t github-actions-riscv:debian-${VERSION} \
            .
      - name: Push Debian Trixie Docker Image
        run: |

          podman tag localhost/github-actions-riscv:debian-${VERSION} docker.io/${{ secrets.DOCKERHUB_USERNAME }}/github-actions-riscv:debian-${VERSION}

          # Login to Docker Hub
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | podman login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

          podman push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/github-actions-riscv:debian-${VERSION}
          
      
      - name: Cleanup local images and containers
        if: always()
        run: |
          echo "Removing local images and any leftover containers..."

          # Remove all local images built for this runner
          podman images -q github-actions-riscv | xargs -r podman rmi -f
