name: Build and Release Debian Github Actions Image

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-runner:
    runs-on: RISCV64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 1. Get numeric-only version (X.Y.Z)
      - name: Get latest runner version
        id: get_version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/alitariq4589/github-runner-riscv/releases/latest \
            | grep -oE '"tag_name":\s*"v?[^"]+' \
            | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"

      # 2. Build Docker image with version ARG
      - name: Build Docker Image
        run: |
          podman build \
            --build-arg RUNNER_VERSION=${VERSION} \
            -t github-actions-riscv:${VERSION} \
            .

      # 3. Push to Docker Hub
      - name: Push Docker Image
        run: |
          
          podman tag localhost/github-actions-riscv:${VERSION} docker.io/${{ secrets.DOCKERHUB_USERNAME }}/github-actions-riscv:latest
          podman tag localhost/github-actions-riscv:${VERSION} docker.io/${{ secrets.DOCKERHUB_USERNAME }}/github-actions-riscv:debian-${VERSION}

          echo "${{ secrets.DOCKERHUB_TOKEN }}" | podman login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          podman push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/github-actions-riscv:latest
          podman push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/github-actions-riscv:debian-${VERSION}
      
      - name: Cleanup local images and containers
        if: always()
        run: |
          echo "Removing local images and any leftover containers..."

          # Remove all local images built for this runner
          podman images -q github-actions-riscv | xargs -r podman rmi -f
